name: Deploy Flask App

on:
  push:
    paths:
      - 'app.py'
      - 'requirements.txt'
      - 'main.tf'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy existing infrastructure
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "${GOOGLE_CREDENTIALS}" > credentials.json
        terraform destroy -auto-approve

    - name: Apply Terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "${GOOGLE_CREDENTIALS}" > credentials.json
        terraform apply -auto-approve
